<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>lrs_halmstad_nav_plugins</name>
  <version>0.0.0</version>
  <description>Nav2 costmap plugins for typed aerial support hazards.</description>
  <maintainer email="tommy.persson@liu.se">tompe</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>builtin_interfaces</depend>
  <depend>geometry_msgs</depend>
  <depend>lrs_halmstad_interfaces</depend>
  <depend>nav2_costmap_2d</depend>
  <depend>pluginlib</depend>
  <depend>rcl_interfaces</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>tf2</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>vision_msgs</depend>

  <test_depend>ament_cmake_gtest</test_depend>
  <test_depend>nav2_util</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
